client_id: dNhSZHWgspNIBDDUZEepgJYH
client_secret: ZhjlX.mZvbaR,zIIgtEu6D0PvQPW9q.Rq4wbY9P+BureO,Z2BsJOlX6LwiKepIIEcl.icH_fhhe7uFCzI-qHZylfMujsbKTKmcUZq8uxpcMH4kqYTkli-RpG5nw-SUi9
secret_bundle_path: C:\Users\somit\Downloads\project_ineuron\insurence_premium_prediction\insurence_premium\cassandra_db\secure-connect-akhil.zip