artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data: artifacts/data_ingestion/raw_data/insurence.csv
  ingested_train_dir: artifacts/data_ingestion/train/insurence.csv
  ingested_test_dir: artifacts/data_ingestion/test/insurence.csv

data_validation:
  root_dir: artifacts/data_validation
  report_file_path: artifacts/data_validation/report.json
  report_page_file_path: artifacts/data_validation/report.html 
  schema_file_path: config/schema.yaml
  
data_transformation:
  root_dir: artifacts/data_transformation
  transformed_train_file_path: artifacts/data_transformation/train/insurence.npz
  transformed_test_file_path: artifacts/data_transformation/test/insurence.npz
  preprocessing_dir:  artifacts/data_transformation/preprocessed_file
  preprocessing_file_path:  artifacts/data_transformation/preprocessed_file/preprocessing.pkl

data_model_trainer:
  root_dir: artifacts/data_model_trainer
  trained_model_file_path: artifacts/data_model_trainer/trained_model/model.pkl
  base_accuracy: 0.6
  model_config_file_path: config/model.yaml

